trigger:
- none

pr:
- none

variables:
  system.debug: 'true'
  ATOMIC_DATA_URL: "http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files/atomic_data_15nov16.tar.gz"
  Hash_Check: "6947fe93c60fd266f8b4fbcaad9c7937  /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz"

jobs:

- job: "Fetch_Atomic_Data"

# Agent pool and vm image
  pool:
    vmImage: "Ubuntu-16.04"
    
  steps:
# Download atomic data for tests
  - bash: |
          mkdir /usr/share/ATOMIC_DATA
          wget $ATOMIC_DATA_URL -O /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz
    displayName: "Fetch atomic data"

  - bash: |
          check=`md5sum /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz`
          echo $check
          echo "$check"
          echo $(Hash_Check)
          echo "$(Hash_Check)"
          if [ "$(Hash_Check)" = "$check" ] ; then
              echo 'test 1 succeeded' 
          fi
          if [ "$Hash_Check" = "$check" ] ; then
              echo 'test 2 succeeded' 
          fi
          if [ $(Hash_Check) = "$check" ] ; then
              echo 'test 3 succeeded' 
          fi
          if [ "$(Hash_Check)" = $check ] ; then
              echo 'test 4 succeeded' 
          fi
    displayName: "debugging"

  - bash: |
          if [ "$(Hash_Check)" = "$check" ] ; then
              echo 'No need to update data' ; else
              tar -zxvf /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz -C /usr/share/ATOMIC_DATA
          fi
    displayName: "Check if data is the same"

