trigger:
- none

pr:
- none

variables:
  ATOMIC_DATA_URL: "http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files/atomic_data_15nov16.tar.gz"
  Hash_Check: "6947fe93c60fd266f8b4fbcaad9c7937  atomic_data_15nov16.tar.gz"

jobs:

- job: "Fetch_Atomic_Data"

# Agent pool and vm image
  pool:
    vmImage: "Ubuntu-16.04"
    
  steps:
# Download atomic data for tests
  - bash: |
          mkdir /usr/share/ATOMIC_DATA
          wget $ATOMIC_DATA_URL -O /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz
    displayName: "Fetch atomic data"

  - bash: |
          check = `md5sum atomic_data_15nov16.tar.gz`
    displayName: "Assign hash value"

  - bash: |
          echo 'No need to update data'
    condition: and(succeeded(), eq(variables['Hash_Check'],check))
    displayName: "Check if data is the same"

  - bash: |
          tar -zxvf /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz -C /usr/share/ATOMIC_DATA
    displayName: "Unload atomic data"
