trigger:
- none

pr:
- none

variables:
  system.debug: 'true'
  ATOMIC_DATA_URL: "http://kookaburra.phyast.pitt.edu/hillier/cmfgen_files/atomic_data_15nov16.tar.gz"

jobs:

- job: "Fetch_Atomic_Data"

# Agent pool and vm image
  pool:
    vmImage: "Ubuntu-16.04"
    
  steps:

# Python script
# Run a Python file or inline script



# Download atomic data for tests
  - bash: |
          mkdir /usr/share/ATOMIC_DATA
          wget $ATOMIC_DATA_URL -O /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz
    displayName: "Fetch atomic data"

  - bash: |
          hash_check_1=`cat hash_check_1`
          echo $hash_check_1
          hash_check_2=`md5sum /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz`
          echo $hash_check_2
          if [ "$hash_check_1" = "$hash_check_2" ]; then
              echo 'No need to update data'; else
              sed -i 's/$hash_check_1/$hash_check_2/g' hash_check_1
              tar -zxvf /usr/share/ATOMIC_DATA/ATOMIC_DATA.gz -C /usr/share/ATOMIC_DATA
          fi
    displayName: "Extract data if updated"

